language: swift

osx_image: xcode10.2

script:
  - xcodebuild -scheme HPFloatMenu -workspace HPFloatMenu.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS:12.2' build test

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
